# @package _global_
defaults:
  - /base
  - /scenario: resco_ingolstadt1
  - /algorithm: ppo_sb3
  - _self_

experiment:
  name: ${scenario.name}__ppo
  seed: 42
  total_timesteps: 50000
  eval_episodes: 5
  eval_seeds: [1, 2, 3, 4, 5]

env:
  factory: parallel_env
  kwargs:
    num_seconds: 3600
    use_gui: false
    add_per_agent_info: true
