# @package _global_
defaults:
  - /base
  - /scenario: resco_ingolstadt1
  - /algorithm: sac_sb3
  - _self_

experiment:
  name: ${scenario.name}__sac
  seed: 42
  total_timesteps: 10000
  eval_episodes: 2

env:
  factory: parallel_env
  kwargs:
    num_seconds: 3600
    use_gui: false
    add_per_agent_info: true
