# @package _global_
defaults:
  - /base
  - /scenario: resco_ingolstadt1
  - /algorithm: static_greedy
  - _self_

experiment:
  name: resco_ingolstadt1__static_greedy
  seeds: [1, 2, 3, 4, 5]
  runs: 5
  episodes: 1
  fixed_ts: false
  total_timesteps: 0
  eval_episodes: 0

env:
  factory: sumo_env
  kwargs:
    num_seconds: 3600
