# @package _global_
scenario:
  name: resco_ingolstadt1

env:
  factory: sumo_env
  kwargs:
    net_file: sumo_rl/nets/RESCO/ingolstadt1/ingolstadt1.net.xml
    route_file: sumo_rl/nets/RESCO/ingolstadt1/ingolstadt1.rou.xml
    begin_time: 25200
    use_gui: false
