# @package _global_
env:
  kwargs:
    use_libsumo: true

algorithm:
  kind: ppo
  params:
    policy_mode: independent
    lr: 0.0005
    gamma: 0.99
    lambda_: 0.95
    clip_param: 0.2
    entropy_coeff: 0.0
    train_batch_size_per_learner: 4000
    sgd_minibatch_size: 128
    num_sgd_iter: 10
