# @package _global_
algorithm:
  kind: sac_rllib_builtin
  params:
    policy_mode: independent
    train_iterations: 10
    actor_lr: 0.0003
    critic_lr: 0.0003
    alpha_lr: 0.0003
    tau: 0.005
    train_batch_size_per_learner: 256
    num_env_runners: 0
    num_envs_per_env_runner: 1
    num_gpus_per_learner: auto
    ray_num_gpus: auto
    num_steps_sampled_before_learning_starts: 1000
