# @package _global_
algorithm:
  kind: sac_builtin
  params:
    policy_mode: independent
    actor_lr: 0.0003
    critic_lr: 0.0003
    alpha_lr: 0.0003
    tau: 0.005
    train_batch_size_per_learner: 256
    num_steps_sampled_before_learning_starts: 1000
