# @package _global_
defaults:
  - /base
  - /scenario: resco_grid4x4
  - /algorithm: baselinev1_rllib
  - _self_

experiment:
  name: ${scenario.name}__baselinev1_rllib
  seed: 42
  runs: 1
  episodes: 1
  total_timesteps: 0
  eval_episodes: 0
  fixed_ts: false

env:
  factory: parallel_env
  kwargs:
    use_gui: false
    out_csv_name: null
    tripinfo_output_name: null
    add_system_info: true
    add_per_agent_info: true
