# @package _global_
defaults:
  - /base
  - /scenario: resco_grid4x4
  - /algorithm: ppo_sb3
  - _self_

experiment:
  name: resco_grid4x4__ppo_sb3
  seed: 42
  total_timesteps: 50000
  eval_episodes: 1

env:
  factory: grid4x4
  kwargs:
    use_gui: true
    out_csv_name: null
    virtual_display:
      - 3200
      - 1800
