defaults:
  - base
  - _self_

experiment:
  name: dqn_2way_single_intersection
  seed: 42
  total_timesteps: 100000
  eval_episodes: 1

env:
  factory: sumo_env
  kwargs:
    net_file: sumo_rl/nets/2way-single-intersection/single-intersection.net.xml
    route_file: sumo_rl/nets/2way-single-intersection/single-intersection-vhvh.rou.xml
    single_agent: true
    use_gui: true
    num_seconds: 100000

algorithm:
  kind: dqn_sb3
  params:
    policy: MlpPolicy
    learning_rate: 0.001
    learning_starts: 0
    train_freq: 1
    target_update_interval: 500
    exploration_initial_eps: 0.05
    exploration_final_eps: 0.01

