defaults:
  - base
  - _self_

experiment:
  name: ql_4x4grid_pz
  seed: 42
  runs: 1
  episodes: 1
  fixed_ts: false

env:
  factory: env
  kwargs:
    net_file: sumo_rl/nets/RESCO/grid4x4/grid4x4.net.xml
    route_file: sumo_rl/nets/RESCO/grid4x4/grid4x4_1.rou.xml
    use_gui: false
    min_green: 8
    delta_time: 5
    num_seconds: 80000

algorithm:
  kind: q_learning
  params:
    alpha: 0.1
    gamma: 0.99
    epsilon: 0.05
    min_epsilon: 0.005
    decay: 1.0
