# @package _global_
defaults:
  - /base
  - /scenario: resco_ingolstadt7
  - /algorithm: libsignal_phase5
  - _self_

experiment:
  name: ${scenario.name}__libsignal_ippo
  seed: 42
  seeds: [1]
  runs: 1
  episodes: 1
  total_timesteps: 0
  eval_episodes: 0

algorithm:
  params:
    libsignal_agent: ppo_pfrl
    libsignal_network: ingolstadt7

env:
  factory: sumo_env
  kwargs:
    single_agent: false
    num_seconds: 3600
    use_gui: false
