# @package _global_
defaults:
  - /rllib
  - override /scenario: resco_ingolstadt21
  - override /algorithm: fgs
  - _self_

experiment:
  name: ${scenario.name}__fgs_mlp_gatv2_sac

algorithm:
  params:
    model_config:
      architecture_tag: fgs_mlp_gatv2_sac
      local_encoder:
        type: mlp
        output_dim: 128
        hidden_dims: [256, 256]
        activation: relu
      communication:
        enabled: true
        type: gatv2
        num_heads: 5
        head_dim: 16
        output_dim: 128
      critic:
        type: central_graph_joint_action
        hidden_dims: [256, 256]
        activation: relu
      topology:
        source: tls_super_edges
        render: true
